// Generated by tools/generate_protocol.py. Do not edit.

export const BOOT_PROTOCOL_VERSION = 2 as const;
export const BOOT_BOARD_ID = 0x48445453 as const;
export const BOOT_BOARD_NAME = "STM32H743VI_UAV" as const;
export const BOOT_MAX_DATA_SIZE = 256 as const;
export const BootCommand = {
  "GET_INFO": 1,
  "BEGIN_UPDATE": 2,
  "WRITE_CHUNK": 3,
  "FINALIZE": 4,
  "REBOOT": 5,
  "GET_STATUS": 6,
  "ABORT": 7,
  "PROTOCOL_ERROR": 127
} as const;
export const BootStatus = {
  "OK": 0,
  "BAD_CRC": 1,
  "BAD_VERSION": 2,
  "UNKNOWN_COMMAND": 3,
  "INVALID_LENGTH": 4,
  "INVALID_STATE": 5,
  "IMAGE_OUT_OF_RANGE": 6,
  "UNEXPECTED_OFFSET": 7,
  "FLASH_ERROR": 8,
  "IMAGE_CRC_MISMATCH": 9,
  "INVALID_VECTOR": 10,
  "RX_OVERFLOW": 11,
  "METADATA_ERROR": 12,
  "ACTIVE_SLOT": 13,
  "SLOT_INVALID": 14,
  "BOARD_MISMATCH": 15,
  "BUSY": 16
} as const;
export const BootSlot = {
  "NONE": 0,
  "A": 1,
  "B": 2
} as const;
