import {createContext,useContext,useEffect,useMemo,useState,type ReactNode} from 'react';
import type {ChartPoint,HilRuntimeStatus,HilState,LinkStats,PortDescriptor,Telemetry,VehicleLog,VehicleParameter} from '../types';
import {initialTelemetry,nextTelemetry} from './telemetry';

const disconnected:LinkStats={connected:false,path:'',rxBytes:0,txBytes:0,rxPackets:0,lostPackets:0,lossRate:0,lastHeartbeat:0,messageRates:{},sources:[],txQueueBytes:0,droppedTx:0,timeOffsetUs:0,timeRttUs:0};
const idleHil:HilRuntimeStatus={phase:'idle',mode:null,reason:'',startedAt:0};
type GpsPoint={lat:number;lon:number};type Message={severity:number;text:string;time:number};
const wrapDegrees=(value:number)=>((value+180)%360+360)%360-180;
const quaternionErrorDegrees=(estimate?:number[],truth?:number[])=>{if(!estimate||!truth||estimate.length<4||truth.length<4)return 0;const en=Math.hypot(...estimate)||1,tn=Math.hypot(...truth)||1,dot=Math.abs(estimate.reduce((sum,value,index)=>sum+value/en*truth[index]/tn,0));return 2*Math.acos(Math.max(-1,Math.min(1,dot)))*180/Math.PI};
 interface FlightValue {telemetry:Telemetry;link:LinkStats;ports:PortDescriptor[];parameters:VehicleParameter[];logs:VehicleLog[];logProgress:{id:number;received:number;total:number}|null;chartData:ChartPoint[];gpsTrail:GpsPoint[];hilState:HilState|null;hilStatus:HilRuntimeStatus;messages:Message[];error:string;demo:boolean;clearCharts():void;refreshPorts():Promise<void>;connect(path:string):Promise<void>;disconnect():Promise<void>;requestParameters():Promise<void>;setParameter(id:string,value:number,type?:number):Promise<void>;exportParameters():Promise<{canceled:boolean;path?:string;count?:number}>;importParameters():Promise<{canceled:boolean;path?:string;parameters:{id:string;value:number;type:number}[]}>;sendCommand(command:number,params?:number[]):Promise<unknown>;testActuator(motor:number,value?:number,duration?:number):Promise<void>;requestLogs():Promise<void>;downloadLog(entry:VehicleLog):Promise<void>;eraseLogs():Promise<void>;startHil(config?:Record<string,unknown>):Promise<void>;pauseHil():Promise<void>;resetHil():Promise<void>;stopHil():Promise<void>;configureHil(config:Record<string,unknown>):Promise<void>;sendRcOverride(channels:number[],release?:boolean):Promise<void>}
const Ctx=createContext<FlightValue|null>(null);

export function FlightProvider({children}:{children:ReactNode}){
 const demo=new URLSearchParams(location.search).get('demo')==='1',zero={...initialTelemetry,roll:0,pitch:0,yaw:0,altitude:0,speed:0,voltage:0,current:0,battery:0,motors:[0,0,0,0],simTime:0,gpsFix:0,satellites:0,lat:0,lon:0,baseMode:0,hilEnabled:false};
 const [telemetry,setTelemetry]=useState<Telemetry>(demo?initialTelemetry:zero),[link,setLink]=useState<LinkStats>(demo?{...disconnected,connected:true,path:'DEMO'}:disconnected),[ports,setPorts]=useState<PortDescriptor[]>([]),[parameters,setParameters]=useState<VehicleParameter[]>([]),[logs,setLogs]=useState<VehicleLog[]>([]),[logProgress,setLogProgress]=useState<{id:number;received:number;total:number}|null>(null),[chartData,setChartData]=useState<ChartPoint[]>([]),[gpsTrail,setGpsTrail]=useState<GpsPoint[]>([]),[hilState,setHilState]=useState<HilState|null>(null),[hilStatus,setHilStatus]=useState<HilRuntimeStatus>(idleHil),[messages,setMessages]=useState<Message[]>([]),[error,setError]=useState('');
 useEffect(()=>{if(demo){const id=setInterval(()=>setTelemetry(value=>nextTelemetry(value,true)),100);return()=>clearInterval(id)}const api=window.aeroLink;if(!api){setError('硬件通信仅在 Electron 桌面程序中可用；浏览器预览请加 ?demo=1。');return}const off=[api.onLink(setLink),api.onTelemetry(value=>{setTelemetry(value);if(value.link)setLink(value.link)}),api.onParameters(setParameters),api.onLogs(setLogs),api.onLogProgress(setLogProgress),api.onHilState(setHilState),api.onHilStatus(setHilStatus),api.onStatusText(message=>setMessages(value=>[message,...value].slice(0,300))),api.onError(value=>setError(value.message))];api.getLinkState().then(setLink).catch(()=>{});api.getHilStatus().then(setHilStatus).catch(()=>{});api.listPorts().then(setPorts).catch(value=>setError(value.message));return()=>off.forEach(fn=>fn())},[demo]);
 useEffect(()=>{if(!demo&&!link.connected&&!hilState?.running)return;const positionError=hilState&&telemetry.positionValid&&telemetry.position?.length===3?Math.hypot(...hilState.position.map((item,index)=>item-(telemetry.position?.[index]||0))):undefined;const attitudeReady=Boolean(hilState&&telemetry.attitudeValid);setChartData(value=>[...value,{t:Date.now(),x:telemetry.imu?.xgyro??0,y:telemetry.imu?.ygyro??0,z:telemetry.imu?.zgyro??0,roll:telemetry.roll,pitch:telemetry.pitch,yaw:telemetry.yaw,truthRoll:hilState?.roll,truthPitch:hilState?.pitch,truthYaw:hilState?.yaw,rollError:attitudeReady?wrapDegrees(telemetry.roll-(hilState?.roll||0)):undefined,pitchError:attitudeReady?wrapDegrees(telemetry.pitch-(hilState?.pitch||0)):undefined,yawError:attitudeReady?wrapDegrees(telemetry.yaw-(hilState?.yaw||0)):undefined,attitudeError:attitudeReady?quaternionErrorDegrees(telemetry.quaternion,hilState?.quaternion):undefined,positionError,m1:(hilState?.controls[0]??telemetry.motors[0]/100)*100,m2:(hilState?.controls[1]??telemetry.motors[1]/100)*100,m3:(hilState?.controls[2]??telemetry.motors[2]/100)*100,m4:(hilState?.controls[3]??telemetry.motors[3]/100)*100,altitude:telemetry.altitude,truthAltitude:hilState?.altitude,voltage:telemetry.voltage,speed:telemetry.speed}].slice(-1200))},[telemetry,hilState,demo,link.connected]);
 useEffect(()=>{if((telemetry.gpsFix||0)<2||!telemetry.lat||!telemetry.lon)return;setGpsTrail(value=>{const last=value.at(-1);if(last&&Math.abs(last.lat-telemetry.lat!)<1e-9&&Math.abs(last.lon-telemetry.lon!)<1e-9)return value;return[...value,{lat:telemetry.lat!,lon:telemetry.lon!}].slice(-3000)})},[telemetry.lat,telemetry.lon,telemetry.gpsFix]);
 const needApi=()=>{if(!window.aeroLink)throw new Error('请在 Electron 桌面程序中运行');return window.aeroLink},call=async<T,>(fn:()=>Promise<T>)=>{setError('');try{return await fn()}catch(value){setError(value instanceof Error?value.message:String(value));throw value}};
 const value=useMemo<FlightValue>(()=>({telemetry,link,ports,parameters,logs,logProgress,chartData,gpsTrail,hilState,hilStatus,messages,error,demo,clearCharts:()=>setChartData([]),refreshPorts:async()=>setPorts(await needApi().listPorts()),connect:async path=>{await call(()=>needApi().connect({path,baudRate:921600,autoReconnect:true}))},disconnect:async()=>{await call(()=>needApi().disconnect())},requestParameters:async()=>{await call(()=>needApi().requestParameters())},setParameter:async(id,paramValue,type=9)=>{await call(()=>needApi().setParameter({id,value:paramValue,type}))},exportParameters:()=>call(()=>needApi().exportParameters()),importParameters:()=>call(()=>needApi().importParameters()),sendCommand:(command,params=[0,0,0,0,0,0,0])=>call(()=>needApi().sendCommand({command,params})),testActuator:async(motor,value=.1,duration=1)=>{if(telemetry.armed)throw new Error('飞控已解锁，禁止执行器测试');if(motor<1||motor>12||value<0||value>1||duration<=0||duration>3)throw new Error('执行器测试参数超出安全范围');await call(()=>needApi().sendCommand({command:310,params:[value,duration,0,0,motor,0,0]}))},requestLogs:async()=>{await call(()=>needApi().listLogs())},downloadLog:async entry=>{setLogProgress({id:entry.id,received:0,total:entry.size});await call(()=>needApi().downloadLog({entry}))},eraseLogs:async()=>{if(telemetry.armed)throw new Error('飞控已解锁，禁止删除板载日志');await call(()=>needApi().eraseLogs())},startHil:async(config={})=>{await call(()=>needApi().startHil(config))},pauseHil:async()=>{await call(()=>needApi().pauseHil())},resetHil:async()=>{await call(()=>needApi().resetHil())},stopHil:async()=>{await call(()=>needApi().stopHil())},configureHil:async config=>{await call(()=>needApi().configureHil(config))},sendRcOverride:async(channels,release=false)=>{await needApi().sendRcOverride({channels,release})}}),[telemetry,link,ports,parameters,logs,logProgress,chartData,gpsTrail,hilState,hilStatus,messages,error,demo]);
 return <Ctx.Provider value={value}>{children}</Ctx.Provider>
}
export const useFlight=()=>{const value=useContext(Ctx);if(!value)throw new Error('FlightProvider missing');return value};
