const test=require('node:test');const assert=require('node:assert/strict');const path=require('path');const {Worker}=require('worker_threads');
const waitFor=(predicate,timeoutMs=2000)=>new Promise((resolve,reject)=>{const started=Date.now();const poll=()=>{if(predicate())return resolve();if(Date.now()-started>=timeoutMs)return reject(new Error(`condition not met within ${timeoutMs} ms`));setTimeout(poll,10)};poll()});
test('HIL worker runs fixed-step sensors, GPS, truth and runtime faults',async()=>{const worker=new Worker(path.join(__dirname,'../electron/hil-engine.cjs'));let sensors=0,gps=0,truth=0,state;worker.on('message',m=>{if(m.type==='sensor')sensors++;if(m.type==='gps')gps++;if(m.type==='truth')truth++;if(m.type==='state')state=m.data});const failed=new Promise((_,reject)=>worker.once('error',reject));worker.postMessage({type:'start',config:{dt:.002,startAltitude:0}});const timer=setInterval(()=>worker.postMessage({type:'actuators',controls:[.55,.55,.55,.55]}),40);const configureTimer=setTimeout(()=>worker.postMessage({type:'configure',config:{motorEfficiency:[1,.8,1,1],sensorDelayMs:4,dropoutRate:.02}}),150);try{await Promise.race([waitFor(()=>sensors>120&&gps>=3&&truth>10&&state?.simTime>.25&&state.config.motorEfficiency[1]===.8),failed])}finally{clearInterval(timer);clearTimeout(configureTimer);await worker.terminate()}assert.ok(state.controls.every(x=>x===.55))});

test('HIL offline preview keeps running without actuator messages',async()=>{const worker=new Worker(path.join(__dirname,'../electron/hil-engine.cjs'));let state;worker.on('message',message=>{if(message.type==='state')state=message.data});worker.postMessage({type:'start',config:{dt:.002,startAltitude:1.5,previewOnly:true}});await new Promise(resolve=>setTimeout(resolve,1750));await worker.terminate();assert.equal(state.mode,'preview');assert.equal(state.running,true);assert.ok(state.simTime>1.4);assert.ok(state.controls.every(value=>value>0&&value<1))});

test('HIL estimator mode sends moving sensor truth without actuator feedback',async()=>{const worker=new Worker(path.join(__dirname,'../electron/hil-engine.cjs'));let state,sensors=0,truth=0,maxRoll=0,warning='';worker.on('message',message=>{if(message.type==='sensor')sensors++;if(message.type==='truth')truth++;if(message.type==='state'){state=message.data;maxRoll=Math.max(maxRoll,Math.abs(state.roll))}if(message.type==='warning')warning=message.message});worker.postMessage({type:'start',config:{dt:.002,startAltitude:2,estimatorOnly:true,trajectory:'combined',noise:{accel:0,gyro:0,mag:0,baro:0,gps:0}}});await new Promise(resolve=>setTimeout(resolve,1750));await worker.terminate();assert.equal(state.mode,'estimator');assert.equal(state.running,true);assert.ok(state.simTime>1.4);assert.ok(sensors>500);assert.ok(truth>50);assert.ok(maxRoll>5,`maxRoll=${maxRoll}`);assert.deepEqual(state.controls,[0,0,0,0]);assert.equal(warning,'')});

test('HIL ground IMU reports gravity and GPS uses MSL altitude',async()=>{const worker=new Worker(path.join(__dirname,'../electron/hil-engine.cjs'));const z=[],gps=[];worker.on('message',message=>{if(message.type==='sensor')z.push(message.data.zacc);if(message.type==='gps')gps.push(message.data)});worker.postMessage({type:'start',config:{dt:.002,startAltitude:0,originAltMsl:12.5,noise:{accel:0,gps:0,gyro:0,mag:0,baro:0}}});const timer=setInterval(()=>worker.postMessage({type:'actuators',controls:[0,0,0,0]}),25);await new Promise(resolve=>setTimeout(resolve,360));clearInterval(timer);await worker.terminate();const mean=z.reduce((sum,value)=>sum+value,0)/z.length;assert.ok(mean<-9.7&&mean>-9.9,`z=${mean}`);assert.ok(gps.length>=2);assert.equal(gps.at(-1).alt,12500)});

test('HIL worker replaces invalid actuator values with safe zeros',async()=>{const worker=new Worker(path.join(__dirname,'../electron/hil-engine.cjs'));let truth,state;worker.on('message',message=>{if(message.type==='truth')truth=message.data;if(message.type==='state')state=message.data});worker.postMessage({type:'start',config:{dt:.002,startAltitude:0}});const timer=setInterval(()=>worker.postMessage({type:'actuators',controls:[NaN,Infinity,-Infinity,undefined]}),20);await new Promise(resolve=>setTimeout(resolve,220));clearInterval(timer);await worker.terminate();assert.deepEqual(state.controls,[0,0,0,0]);assert.ok([...truth.q,...truth.w,...truth.p,...truth.v,...truth.specific].every(Number.isFinite))});
