const test=require('node:test');const assert=require('node:assert/strict');const {EventEmitter}=require('events');
const {VehicleSession,mavlink20}=require('../electron/vehicle-session.cjs');const {MAVLink20Processor}=require('../electron/mavlink/generated.js');
class Link extends EventEmitter{constructor(){super();this.port={isOpen:true};this.config={path:'MOCK'};this.stats={rxBytes:0,txBytes:0};this.frames=[]}write(data,priority){this.frames.push({data:Buffer.from(data),priority});this.stats.txBytes+=data.length;return Promise.resolve()}}
function fcFrame(fc,msg,rawInt){const b=Buffer.from(msg.pack(fc));if(rawInt!==undefined){b.writeInt32LE(rawInt,10);const c1=mavlink20.x25Crc(b.subarray(1,10+b[1])),c2=mavlink20.x25Crc([msg.crc_extra],c1);b.writeUInt16LE(c2,10+b[1])}fc.seq=(fc.seq+1)&255;return b}
function inject(link,fc,msg,raw){const b=fcFrame(fc,msg,raw);link.stats.rxBytes+=b.length;link.emit('data',b)}
test('parameter list requests missing indexes and confirms INT32 write',async()=>{const link=new Link(),session=new VehicleSession(link,'',{replay:true}),fc=new MAVLink20Processor(null,1,1);session.requestParameters();inject(link,fc,new mavlink20.messages.param_value('P0',1,9,3,0));inject(link,fc,new mavlink20.messages.param_value('P2',2,9,3,2));await new Promise(r=>setTimeout(r,430));const parser=new MAVLink20Processor(null,1,1),sent=link.frames.flatMap(x=>parser.parseBuffer(x.data)||[]),missing=sent.find(x=>x._name==='PARAM_REQUEST_READ');assert.equal(missing.param_index,1);const pending=session.setParameter('I32',-42,6);inject(link,fc,new mavlink20.messages.param_value('I32',0,6,4,3),-42);const ack=await pending;assert.equal(ack.value,-42);const paramSet=link.frames.map(x=>new MAVLink20Processor(null,1,1).parseBuffer(x.data)?.[0]).find(x=>x?._name==='PARAM_SET');assert.equal(Buffer.from(paramSet._payload).readInt32LE(0),-42);session.dispose()});
test('command resolves ACK and rejects denied result',async()=>{const link=new Link(),session=new VehicleSession(link,'',{replay:true}),fc=new MAVLink20Processor(null,1,1);const ok=session.command(401);inject(link,fc,new mavlink20.messages.command_ack(401,0,100,0,255,190));assert.equal((await ok).result,0);const denied=session.command(310,[0,1,0,0,33,0,0]);inject(link,fc,new mavlink20.messages.command_ack(310,2,0,0,255,190));await assert.rejects(denied,/MAV_RESULT=2/);session.dispose()});

test('heartbeat confirms HIL state and exposes per-source statistics',async()=>{const link=new Link(),session=new VehicleSession(link,'',{replay:true}),fc=new MAVLink20Processor(null,1,1),confirmed=session.waitForHilState(true,300);inject(link,fc,new mavlink20.messages.heartbeat(2,0,32,0,4));await confirmed;assert.equal(session.telemetry.hilEnabled,true);assert.equal(session.telemetry.baseMode,32);const stats=session.linkStats();assert.equal(stats.sources.length,1);assert.equal(stats.sources[0].systemId,1);assert.equal(stats.sources[0].componentId,1);session.dispose()});

test('MAVLink loss statistics handle wrap and ignore duplicate or reordered frames',()=>{const link=new Link(),session=new VehicleSession(link,'',{replay:true}),fc=new MAVLink20Processor(null,1,1),heartbeat=()=>new mavlink20.messages.heartbeat(2,0,0,0,4);fc.seq=254;inject(link,fc,heartbeat());inject(link,fc,heartbeat());inject(link,fc,heartbeat());fc.seq=2;inject(link,fc,heartbeat());fc.seq=1;inject(link,fc,heartbeat());fc.seq=3;inject(link,fc,heartbeat());const stats=session.linkStats();assert.equal(stats.lostPackets,1);assert.equal(stats.sources[0].lostPackets,1);session.dispose()});

test('HIL packets sanitize non-finite and out-of-range values',async()=>{const link=new Link(),session=new VehicleSession(link,'',{replay:true});await session.sendHilSensor({timeUsec:Infinity,xacc:NaN,zacc:-Infinity});await session.sendHilGps({timeUsec:Infinity,lat:Infinity,lon:-Infinity,alt:Infinity,vn:1e9,ve:-1e9});await session.sendHilTruth({timeUsec:Infinity,q:[NaN,Infinity,0,0],w:[Infinity,NaN,-Infinity],p:[Infinity,NaN,-Infinity],v:[1e9,-1e9,Infinity],specific:[Infinity,NaN,-Infinity],originLat:Infinity,originLon:NaN,originAltMsl:Infinity});const parser=new MAVLink20Processor(null,1,1),messages=link.frames.flatMap(frame=>parser.parseBuffer(frame.data)||[]);assert.deepEqual(messages.map(message=>message._name),['HIL_SENSOR','HIL_GPS','HIL_STATE_QUATERNION']);const truth=messages[2],truthFrame=link.frames[2].data;assert.deepEqual(truth.attitude_quaternion,[1,0,0,0]);assert.equal(truthFrame.readInt16LE(10+48),32767);assert.equal(truthFrame.readInt16LE(10+50),-32768);assert.ok(Number.isFinite(truth.rollspeed));session.dispose()});

test('MAVLink packing failures are returned as rejected promises',async()=>{const link=new Link(),session=new VehicleSession(link,'',{replay:true});let result;assert.doesNotThrow(()=>{result=session.send({_name:'BROKEN_PACKET',pack(){throw new Error('bad payload')}})});await assert.rejects(result,/BROKEN_PACKET.*bad payload/);session.dispose()});

test('virtual RC sends standard override channels and releases safely',async()=>{const link=new Link(),session=new VehicleSession(link,'',{replay:true});await session.sendRcOverride([1600,1400,1000,1500,2000,1000]);await session.sendRcOverride([],true);const parser=new MAVLink20Processor(null,1,1),messages=link.frames.flatMap(frame=>parser.parseBuffer(frame.data)||[]);assert.deepEqual(messages.map(message=>message._name),['RC_CHANNELS_OVERRIDE','RC_CHANNELS_OVERRIDE']);assert.deepEqual([messages[0].chan1_raw,messages[0].chan2_raw,messages[0].chan3_raw,messages[0].chan4_raw,messages[0].chan5_raw,messages[0].chan6_raw],[1600,1400,1000,1500,2000,1000]);assert.deepEqual([messages[1].chan1_raw,messages[1].chan2_raw,messages[1].chan3_raw,messages[1].chan4_raw],[0,0,0,0]);session.dispose()});
