const {parentPort,workerData}=require('worker_threads');
const {EventEmitter}=require('events');
const fs=require('fs');
const {VehicleSession}=require('./vehicle-session.cjs');
class ReplayLink extends EventEmitter{constructor(){super();this.port=null;this.config={path:workerData.file};this.stats={rxBytes:0,txBytes:0}}write(){return Promise.resolve()}}
const link=new ReplayLink(),session=new VehicleSession(link,'',{replay:true}),charts=[],trail=[],events=[];let now=0,lastSample=-Infinity;
session.on('telemetry',t=>{if(now-lastSample<50000)return;lastSample=now;charts.push({t:Math.round(now/1000),x:t.imu?.xgyro||0,y:t.imu?.ygyro||0,z:t.imu?.zgyro||0,roll:t.roll,pitch:t.pitch,yaw:t.yaw,m1:t.motors[0]||0,m2:t.motors[1]||0,m3:t.motors[2]||0,m4:t.motors[3]||0,altitude:t.altitude,voltage:t.voltage,speed:t.speed,lat:t.lat||0,lon:t.lon||0});if((t.gpsFix||0)>=2&&t.lat&&t.lon){const p={lat:t.lat,lon:t.lon};const last=trail.at(-1);if(!last||last.lat!==p.lat||last.lon!==p.lon)trail.push(p)}});
session.on('statusText',m=>events.push({...m,t:now}));
function frameLength(buffer,offset){const magic=buffer[offset];if(magic===0xfd){if(offset+10>buffer.length)return 0;return 10+buffer[offset+1]+2+((buffer[offset+2]&1)?13:0)}if(magic===0xfe){if(offset+6>buffer.length)return 0;return 6+buffer[offset+1]+2}return 0}
try{const buf=fs.readFileSync(workerData.file);let offset=0,records=0,format='raw MAVLink';const standard=buf.length>9&&(buf[8]===0xfd||buf[8]===0xfe),legacy=buf.length>11&&(buf[10]===0xfd||buf[10]===0xfe);if(standard){format='MAVLink standard tlog';while(offset+9<=buf.length){now=Number(buf.readBigUInt64BE(offset));const start=offset+8,len=frameLength(buf,start);if(!len||start+len>buf.length)break;const frame=buf.subarray(start,start+len);offset=start+len;link.stats.rxBytes+=len;session.feed(frame);records++}}else if(legacy){format='AeroLink legacy tlog';while(offset+10<=buf.length){now=Number(buf.readBigUInt64LE(offset));const len=buf.readUInt16LE(offset+8);offset+=10;if(!len||offset+len>buf.length)break;const frame=buf.subarray(offset,offset+len);offset+=len;link.stats.rxBytes+=len;session.feed(frame);records++}}else{now=Date.now()*1000;for(offset=0;offset<buf.length;offset+=4096){const chunk=buf.subarray(offset,Math.min(buf.length,offset+4096));link.stats.rxBytes+=chunk.length;session.feed(chunk);now+=20000;records++}}session.dispose();const stride=Math.max(1,Math.ceil(charts.length/20000)),sampled=charts.filter((_,index)=>index%stride===0);parentPort.postMessage({ok:true,data:{file:workerData.file,size:buf.length,format,records,durationUs:sampled.length?sampled.at(-1).t*1000-sampled[0].t*1000:0,charts:sampled,trail,events,final:session.telemetry,link:session.linkStats()}})}catch(error){session.dispose();parentPort.postMessage({ok:false,error:error.message})}
