const {EventEmitter}=require('events');
const {SerialPort}=require('serialport');
const MAX_QUEUE_BYTES=2*1024*1024;
class SerialLink extends EventEmitter{
 constructor(PortClass=SerialPort){super();this.PortClass=PortClass;this.port=null;this.config=null;this.reconnectTimer=null;this.manualClose=false;this.txQueues=[[],[],[],[]];this.writing=false;this.stats={rxBytes:0,txBytes:0,openedAt:0,lastRxAt:0,lastTxAt:0,txQueueBytes:0,droppedTx:0,maxQueueBytes:0}}
 static async list(listFn=SerialPort.list.bind(SerialPort)){const ports=await listFn();return ports.map(port=>({path:port.path,manufacturer:port.manufacturer||'',serialNumber:port.serialNumber||'',vendorId:port.vendorId||'',productId:port.productId||'',friendlyName:port.friendlyName||port.path}))}
 async open(config){await this.close(true);this.config={baudRate:921600,autoReconnect:true,...config};this.manualClose=false;return new Promise((resolve,reject)=>{const port=new this.PortClass({path:this.config.path,baudRate:this.config.baudRate,autoOpen:false,lock:true,highWaterMark:65536});this.port=port;port.on('data',data=>{this.stats.rxBytes+=data.length;this.stats.lastRxAt=Date.now();this.emit('data',data)});port.on('error',error=>this.emit('error',error));port.on('close',error=>{this.writing=false;this.rejectQueued('USB CDC 已断开');this.emit('close',error);if(!this.manualClose&&this.config?.autoReconnect)this.scheduleReconnect()});port.open(error=>{if(error){this.port=null;reject(error);if(this.config?.autoReconnect)this.scheduleReconnect();return}this.stats={...this.stats,openedAt:Date.now(),txQueueBytes:0};this.emit('open',this.config);resolve()})})}
 rejectQueued(reason){for(const queue of this.txQueues)for(const item of queue.splice(0)){this.stats.txQueueBytes-=item.data.length;item.reject(new Error(reason))}this.stats.txQueueBytes=Math.max(0,this.stats.txQueueBytes)}
 async close(internal=false){if(!internal)this.manualClose=true;if(this.reconnectTimer){clearTimeout(this.reconnectTimer);this.reconnectTimer=null}const port=this.port;this.port=null;this.rejectQueued('连接已关闭');if(port?.isOpen)await new Promise(resolve=>port.close(()=>resolve()))}
 scheduleReconnect(){if(this.reconnectTimer||!this.config||this.manualClose)return;this.reconnectTimer=setTimeout(async()=>{this.reconnectTimer=null;try{await this.open(this.config)}catch(error){this.emit('error',error);this.scheduleReconnect()}},1500)}
 makeRoom(required,priority){while(this.stats.txQueueBytes+required>MAX_QUEUE_BYTES){let removed=null;for(let index=3;index>=Math.max(priority,1);index--)if(this.txQueues[index].length){removed=this.txQueues[index].shift();break}if(!removed)return false;this.stats.txQueueBytes-=removed.data.length;this.stats.droppedTx++;removed.resolve({dropped:true,reason:'backpressure'})}return true}
 write(data,priority=1,options={}){if(!this.port?.isOpen)return Promise.reject(new Error('USB CDC 未连接'));const buffer=Buffer.from(data),queueIndex=Math.max(0,Math.min(3,priority));return new Promise((resolve,reject)=>{const queue=this.txQueues[queueIndex];if(options.replaceKey){const existing=queue.find(item=>item.replaceKey===options.replaceKey);if(existing){this.stats.txQueueBytes+=buffer.length-existing.data.length;existing.data=buffer;this.stats.droppedTx++;resolve({dropped:true,reason:'superseded'});return}}if(!this.makeRoom(buffer.length,queueIndex)){this.stats.droppedTx++;reject(new Error(`TX 队列已满（${MAX_QUEUE_BYTES} bytes）`));return}queue.push({data:buffer,resolve,reject,replaceKey:options.replaceKey});this.stats.txQueueBytes+=buffer.length;this.stats.maxQueueBytes=Math.max(this.stats.maxQueueBytes,this.stats.txQueueBytes);this.flush()})}
 flush(){if(this.writing||!this.port?.isOpen)return;let item;for(const queue of this.txQueues)if(queue.length){item=queue.shift();break}if(!item)return;this.stats.txQueueBytes=Math.max(0,this.stats.txQueueBytes-item.data.length);this.writing=true;this.port.write(item.data,error=>{this.writing=false;if(error)item.reject(error);else{this.stats.txBytes+=item.data.length;this.stats.lastTxAt=Date.now();item.resolve({written:true})}this.flush()})}
}
module.exports={SerialLink,MAX_QUEUE_BYTES};
