const {EventEmitter}=require('events');
const fs=require('fs');
const path=require('path');
const {performance}=require('perf_hooks');
const {mavlink20,MAVLink20Processor}=require('./mavlink/generated.js');

const G=9.80665,PARAM_TIMEOUT=1000,COMMAND_TIMEOUT=1000,MAV_PARAM_TYPE_INT32=6,MAV_PARAM_TYPE_REAL32=9;
const monoUs=()=>Math.round(performance.now()*1000);
const int64ToNumber=value=>Array.isArray(value)?(Number(value[0])>>>0)+(Number(value[1])>>>0)*0x100000000:Number(value||0);
const finite=(value,fallback=0)=>Number.isFinite(Number(value))?Number(value):fallback;
const bounded=(value,min,max,fallback=0)=>Math.max(min,Math.min(max,finite(value,fallback)));
const integer=(value,min,max,fallback=0)=>Math.round(bounded(value,min,max,fallback));
const float32=(value,fallback=0)=>bounded(value,-3.402823466e38,3.402823466e38,fallback);
const vector=(value,length,fallback=0)=>Array.from({length},(_,index)=>finite(value?.[index],fallback));
const quaternion=value=>{const q=vector(value,4,0),norm=Math.hypot(...q);return Number.isFinite(norm)&&norm>1e-9?q.map(component=>component/norm):[1,0,0,0]};
const uint64Pair=value=>{const numeric=finite(value,0),n=BigInt(Math.max(0,Math.trunc(numeric)));return[Number(n&0xffffffffn),Number((n>>32n)&0xffffffffn),true]};
const cleanString=value=>Array.isArray(value)?String.fromCharCode(...value).replace(/\0.*$/,''):String(value??'').replace(/\0.*$/,'');
const quaternionToEuler=q=>{const[w,x,y,z]=q;return{roll:Math.atan2(2*(w*x+y*z),1-2*(x*x+y*y))*180/Math.PI,pitch:Math.asin(Math.max(-1,Math.min(1,2*(w*y-z*x))))*180/Math.PI,yaw:(Math.atan2(2*(w*z+x*y),1-2*(y*y+z*z))*180/Math.PI+360)%360}};
function encodeParam(value,type){if(type!==MAV_PARAM_TYPE_INT32)return Number(value);const b=Buffer.alloc(4);b.writeInt32LE(Math.trunc(value));return b.readFloatLE(0)}
function decodeParam(value,type,raw){if(type!==MAV_PARAM_TYPE_INT32)return Number(value);if(raw&&raw.length>=4)return Buffer.from(raw).readInt32LE(0);const b=Buffer.alloc(4);b.writeFloatLE(Number(value));return b.readInt32LE(0)}

class VehicleSession extends EventEmitter{
 constructor(link,logRoot,options={}){
  super();this.link=link;this.logRoot=logRoot;this.replay=!!options.replay;this.mav=new MAVLink20Processor(null,255,190);this.target={systemId:1,componentId:1};this.connected=false;this.bootstrapped=false;this.lastHeartbeat=0;this.params=new Map();this.paramPending=new Map();this.paramSync=null;this.commandPending=new Map();this.logEntries=new Map();this.download=null;this.rxSeq=new Map();this.sourceStats=new Map();this.lostPackets=0;this.rxPackets=0;this.msgRates=new Map();this.tlog=null;this.tlogPath='';this.pingSent=new Map();this.timeSync={offsetUs:0,rttUs:0,samples:0};
  this.telemetry={roll:0,pitch:0,yaw:0,altitude:0,speed:0,voltage:0,current:0,battery:0,latency:0,cpu:0,motors:[0,0,0,0],simTime:0,gpsFix:0,satellites:0,lat:0,lon:0,quaternion:[1,0,0,0],position:[0,0,0],velocity:[0,0,0],attitudeValid:false,positionValid:false,imu:{xacc:0,yacc:0,zacc:0,xgyro:0,ygyro:0,zgyro:0},armed:false,baseMode:0,hilEnabled:false,mode:0,ekfFlags:0};
  link.on('data',d=>this.feed(d));link.on('open',()=>this.start());link.on('close',()=>this.stop('串口已关闭'));link.on('error',e=>this.emit('error',e));this.monitor=this.replay?null:setInterval(()=>this.housekeeping(),250);
 }
 dispose(){if(this.monitor)clearInterval(this.monitor);this.stop('会话结束')}
 start(){this.openTlog();this.sendHeartbeat();clearInterval(this.heartbeatTimer);clearInterval(this.pingTimer);this.heartbeatTimer=setInterval(()=>this.sendHeartbeat(),1000);this.pingTimer=setInterval(()=>this.sendPing(),1000);this.emitLink()}
 stop(reason){clearInterval(this.heartbeatTimer);clearInterval(this.pingTimer);this.heartbeatTimer=this.pingTimer=null;this.connected=false;this.bootstrapped=false;this.closeTlog();this.rejectAll(reason);this.cancelDownload(reason);this.emitLink()}
 rejectAll(reason){for(const p of this.paramPending.values()){clearTimeout(p.timer);p.reject(new Error(reason))}for(const p of this.commandPending.values()){clearTimeout(p.timer);p.reject(new Error(reason))}this.paramPending.clear();this.commandPending.clear();if(this.paramSync?.timer)clearTimeout(this.paramSync.timer);this.paramSync=null}
 openTlog(){try{fs.mkdirSync(this.logRoot,{recursive:true});const stamp=new Date().toISOString().replace(/[:.]/g,'-');this.tlogPath=path.join(this.logRoot,`flight-${stamp}.tlog`);this.tlog=fs.createWriteStream(this.tlogPath,{flags:'a'})}catch(e){this.emit('error',e)}}
 closeTlog(){if(this.tlog){this.tlog.end();try{fs.writeFileSync(`${this.tlogPath}.json`,JSON.stringify({format:'mavlink-standard-tlog',createdAt:new Date().toISOString(),target:this.target,link:this.linkStats()},null,2))}catch{}}this.tlog=null}
 recordFrame(data){if(!this.tlog||!data?.length)return;const stamp=Buffer.alloc(8);stamp.writeBigUInt64BE(BigInt(Date.now())*1000n);this.tlog.write(stamp);this.tlog.write(Buffer.from(data))}
 feed(data){let messages;try{messages=this.mav.parseBuffer(new Uint8Array(data))||[]}catch(e){this.emit('error',e);return}for(const msg of messages){if(msg._name==='BAD_DATA')continue;this.recordFrame(msg._msgbuf);this.track(msg);this.handle(msg)}}
 track(msg){this.rxPackets++;const h=msg._header||{},key=`${h.srcSystem||0}:${h.srcComponent||0}`,sequence=h.seq??h.sequence,old=this.rxSeq.get(key);let lost=0,advance=sequence!=null;if(old!=null&&sequence!=null){const gap=(sequence-old+256)%256;if(gap>1&&gap<128){lost=gap-1;this.lostPackets+=lost}else if(gap===0||gap>=128)advance=false}if(advance)this.rxSeq.set(key,sequence);const now=Date.now(),source=this.sourceStats.get(key)||{systemId:h.srcSystem||0,componentId:h.srcComponent||0,rxPackets:0,lostPackets:0,lastRxAt:0,messageRates:{},rateCounters:{}};source.rxPackets++;source.lostPackets+=lost;source.lastRxAt=now;const sourceRate=source.rateCounters[msg._name]||{count:0,since:now,hz:0};sourceRate.count++;if(now-sourceRate.since>=1000){sourceRate.hz=sourceRate.count*1000/(now-sourceRate.since);sourceRate.count=0;sourceRate.since=now}source.rateCounters[msg._name]=sourceRate;source.messageRates[msg._name]=sourceRate.hz;this.sourceStats.set(key,source);const rate=this.msgRates.get(msg._name)||{count:0,since:now,hz:0};rate.count++;if(now-rate.since>=1000){rate.hz=rate.count*1000/(now-rate.since);rate.count=0;rate.since=now}this.msgRates.set(msg._name,rate)}
 handle(m){
  switch(m._name){
   case'HEARTBEAT':{const first=!this.connected;this.target={systemId:m._header.srcSystem,componentId:m._header.srcComponent};this.lastHeartbeat=Date.now();this.connected=true;this.telemetry.armed=!!(m.base_mode&128);this.telemetry.baseMode=m.base_mode;this.telemetry.hilEnabled=!!(m.base_mode&32);this.telemetry.mode=m.custom_mode;this.emit('heartbeat',{...this.telemetry});this.emitLink();if(first&&!this.bootstrapped&&!this.replay){this.bootstrapped=true;setTimeout(()=>this.bootstrap().catch(e=>this.emit('error',e)),100)}break}
   case'ATTITUDE':Object.assign(this.telemetry,{roll:m.roll*180/Math.PI,pitch:m.pitch*180/Math.PI,yaw:(m.yaw*180/Math.PI+360)%360});break;
    case'ATTITUDE_QUATERNION':this.telemetry.quaternion=[m.q1,m.q2,m.q3,m.q4];this.telemetry.attitudeValid=true;Object.assign(this.telemetry,quaternionToEuler(this.telemetry.quaternion));break;
    case'LOCAL_POSITION_NED':this.telemetry.position=[m.x,m.y,m.z];this.telemetry.velocity=[m.vx,m.vy,m.vz];this.telemetry.positionValid=true;this.telemetry.altitude=-m.z;this.telemetry.speed=Math.hypot(m.vx,m.vy);break;
   case'GLOBAL_POSITION_INT':Object.assign(this.telemetry,{lat:m.lat/1e7,lon:m.lon/1e7,altitude:m.relative_alt/1000,speed:Math.hypot(m.vx,m.vy)/100,yaw:m.hdg===65535?this.telemetry.yaw:m.hdg/100});break;
   case'GPS_RAW_INT':Object.assign(this.telemetry,{gpsFix:m.fix_type,satellites:m.satellites_visible,lat:m.lat/1e7,lon:m.lon/1e7});break;
   case'HIGHRES_IMU':this.telemetry.imu={xacc:m.xacc,yacc:m.yacc,zacc:m.zacc,xgyro:m.xgyro,ygyro:m.ygyro,zgyro:m.zgyro};break;
   case'SYS_STATUS':this.telemetry.voltage=m.voltage_battery===65535?this.telemetry.voltage:m.voltage_battery/1000;this.telemetry.current=m.current_battery===-1?this.telemetry.current:m.current_battery/100;this.telemetry.battery=m.battery_remaining;break;
   case'BATTERY_STATUS':this.telemetry.voltage=(m.voltages?.find(v=>v!==65535)||0)/1000;this.telemetry.current=m.current_battery===-1?this.telemetry.current:m.current_battery/100;this.telemetry.battery=m.battery_remaining;break;
   case'ACTUATOR_OUTPUT_STATUS':this.telemetry.motors=(m.actuator||[]).slice(0,4).map(v=>Math.round(Math.max(0,Math.min(1,v))*100));break;
   case'SERVO_OUTPUT_RAW':this.telemetry.motors=[m.servo1_raw,m.servo2_raw,m.servo3_raw,m.servo4_raw].map(v=>Math.round(Math.max(0,Math.min(100,(v-1000)/10))));break;
   case'ESTIMATOR_STATUS':this.telemetry.ekfFlags=m.flags;break;
   case'CURRENT_MODE':this.telemetry.mode=m.custom_mode;break;
   case'PARAM_VALUE':this.onParam(m);break;
   case'COMMAND_ACK':this.onCommandAck(m);break;
   case'LOG_ENTRY':this.onLogEntry(m);break;
   case'LOG_DATA':this.onLogData(m);break;
   case'PING':if(m.target_system===255&&m.target_component===190){const sent=this.pingSent.get(m.seq);if(sent!=null){this.telemetry.latency=Math.max(0,(monoUs()-sent)/2000);this.pingSent.delete(m.seq)}}break;
   case'TIMESYNC':{const tc1=int64ToNumber(m.tc1),ts1=int64ToNumber(m.ts1);if(tc1===0)this.send(new mavlink20.messages.timesync(uint64Pair(monoUs()),uint64Pair(ts1)),0).catch(()=>{});else{const now=monoUs(),rtt=now-ts1,offset=tc1-(ts1+rtt/2);if(rtt>=0&&rtt<1e6){const alpha=this.timeSync.samples ? .15 : 1;this.timeSync.offsetUs=this.timeSync.offsetUs*(1-alpha)+offset*alpha;this.timeSync.rttUs=rtt;this.timeSync.samples++}}break}
   case'HIL_ACTUATOR_CONTROLS':this.emit('hil-actuators',{timeUsec:int64ToNumber(m.time_usec),controls:m.controls,mode:m.mode,flags:int64ToNumber(m.flags)});break;
   case'STATUSTEXT':this.emit('statusText',{severity:m.severity,text:cleanString(m.text),time:Date.now()});break;
  }
  this.emit('telemetry',{...this.telemetry,link:this.linkStats()});
 }
 async bootstrap(){this.send(new mavlink20.messages.timesync(uint64Pair(0),uint64Pair(monoUs())),0).catch(()=>{});this.requestParameters();try{await this.requestAutopilotVersion()}catch{}const desired=[[31,50],[105,100],[32,20],[33,10],[24,5],[147,2],[375,50],[230,5],[245,2]];for(const[id,hz]of desired){if(!this.connected)break;try{await this.setMessageInterval(id,hz)}catch{break}}}
 send(message,priority=1,options){if(!this.link.port?.isOpen)return Promise.reject(new Error('USB CDC 未连接'));let data;try{data=message.pack(this.mav);this.mav.seq=(this.mav.seq+1)%256;this.mav.total_packets_sent++;this.mav.total_bytes_sent+=data.length;this.recordFrame(data);return Promise.resolve(this.link.write(data,priority,options))}catch(error){return Promise.reject(new Error(`${message?._name||'MAVLink'} 编码失败：${error.message}`,{cause:error}))}}
 sendParameterSet(id,value,type){if(type!==MAV_PARAM_TYPE_INT32)return this.send(new mavlink20.messages.param_set(this.target.systemId,this.target.componentId,id,value,type),2);if(!this.link.port?.isOpen)return Promise.reject(new Error('USB CDC 未连接'));const message=new mavlink20.messages.param_set(this.target.systemId,this.target.componentId,id,0,type),data=Buffer.from(message.pack(this.mav)),payloadOffset=10;data.writeInt32LE(Math.trunc(value),payloadOffset);const payloadLength=data[1],crc1=mavlink20.x25Crc(data.subarray(1,payloadOffset+payloadLength)),crc2=mavlink20.x25Crc([message.crc_extra],crc1);data.writeUInt16LE(crc2,payloadOffset+payloadLength);this.mav.seq=(this.mav.seq+1)%256;this.mav.total_packets_sent++;this.mav.total_bytes_sent+=data.length;this.recordFrame(data);return this.link.write(data,2)}
 sendHeartbeat(){if(!this.link.port?.isOpen)return;this.send(new mavlink20.messages.heartbeat(6,8,0,0,4),0).catch(()=>{})}
 sendPing(){if(!this.link.port?.isOpen)return;this.pingSequence=((this.pingSequence||0)+1)>>>0;const sent=monoUs();this.pingSent.set(this.pingSequence,sent);while(this.pingSent.size>8)this.pingSent.delete(this.pingSent.keys().next().value);this.send(new mavlink20.messages.ping(uint64Pair(sent),this.pingSequence,this.target.systemId,this.target.componentId),0).catch(()=>{})}
 housekeeping(){if(this.connected&&Date.now()-this.lastHeartbeat>5000){this.connected=false;this.bootstrapped=false;this.emitLink()}this.emit('telemetry',{...this.telemetry,link:this.linkStats()})}
 linkStats(){const total=this.rxPackets+this.lostPackets;return{connected:this.connected,path:this.link.config?.path||'',rxBytes:this.link.stats.rxBytes,txBytes:this.link.stats.txBytes,rxPackets:this.rxPackets,lostPackets:this.lostPackets,lossRate:total?this.lostPackets/total*100:0,lastHeartbeat:this.lastHeartbeat,messageRates:Object.fromEntries([...this.msgRates].map(([k,v])=>[k,v.hz])),sources:[...this.sourceStats.values()].map(source=>({...source,rateCounters:undefined,lossRate:(source.rxPackets+source.lostPackets)?source.lostPackets/(source.rxPackets+source.lostPackets)*100:0})),txQueueBytes:this.link.stats.txQueueBytes||0,droppedTx:this.link.stats.droppedTx||0,timeOffsetUs:Math.round(this.timeSync.offsetUs),timeRttUs:Math.round(this.timeSync.rttUs)}}
 emitLink(){this.emit('link',this.linkStats())}
 requestAutopilotVersion(){return this.command(512,[148,0,0,0,0,0,0])}
 setMessageInterval(messageId,hz){return this.command(511,[messageId,hz>0?1e6/hz:-1,0,0,0,0,0])}
 requestParameters(){this.params.clear();if(this.paramSync?.timer)clearTimeout(this.paramSync.timer);this.paramSync={expected:0,received:new Set(),round:0,timer:null};this.send(new mavlink20.messages.param_request_list(this.target.systemId,this.target.componentId),2).catch(e=>this.emit('error',e));return{started:true}}
 onParam(m){const id=cleanString(m.param_id),value=decodeParam(m.param_value,m.param_type,m._payload),item={id,value,type:m.param_type,index:m.param_index,count:m.param_count,componentId:m._header.srcComponent};this.params.set(`${item.componentId}:${id}`,item);this.emit('parameters',[...this.params.values()].sort((a,b)=>a.index-b.index));if(this.paramSync){this.paramSync.expected=Math.max(this.paramSync.expected,item.count);if(item.index>=0)this.paramSync.received.add(item.index);clearTimeout(this.paramSync.timer);this.paramSync.timer=setTimeout(()=>this.checkMissingParams(),350)}const p=this.paramPending.get(id);if(p&&item.type===p.type&&Math.abs(Number(item.value)-Number(p.value))<=p.epsilon){clearTimeout(p.timer);this.paramPending.delete(id);p.resolve(item)}}
 checkMissingParams(){const s=this.paramSync;if(!s)return;const missing=[];for(let i=0;i<s.expected;i++)if(!s.received.has(i))missing.push(i);if(!missing.length&&s.expected){this.emit('parameterSync',{complete:true,received:s.received.size,expected:s.expected});this.paramSync=null;return}if(s.round>=3){this.emit('error',new Error(`参数同步缺少 ${missing.length} 项`));return}s.round++;for(const index of missing.slice(0,128))this.send(new mavlink20.messages.param_request_read(this.target.systemId,this.target.componentId,'',index),2).catch(()=>{});s.timer=setTimeout(()=>this.checkMissingParams(),750)}
 setParameter(id,value,type=MAV_PARAM_TYPE_REAL32){if(Buffer.byteLength(id,'utf8')>16)throw new Error('参数名不能超过 16 字节');if(type!==MAV_PARAM_TYPE_REAL32&&type!==MAV_PARAM_TYPE_INT32)throw new Error(`暂不支持 MAV_PARAM_TYPE=${type}`);if(this.paramPending.has(id))return Promise.reject(new Error(`参数 ${id} 正在写入`));return new Promise((resolve,reject)=>{const pending={value,type,epsilon:type===MAV_PARAM_TYPE_REAL32?1e-5:0,attempt:0,timer:null,resolve,reject};const attempt=()=>{pending.attempt++;this.sendParameterSet(id,value,type).catch(reject);pending.timer=setTimeout(()=>{if(pending.attempt<3)attempt();else{this.paramPending.delete(id);reject(new Error(`参数 ${id} 写入超时`))}},PARAM_TIMEOUT)};this.paramPending.set(id,pending);attempt()})}
 command(command,params=[0,0,0,0,0,0,0]){if(this.commandPending.has(command))return Promise.reject(new Error(`命令 ${command} 正在执行`));return new Promise((resolve,reject)=>{const p={attempt:0,timer:null,resolve,reject,params};const attempt=()=>{p.attempt++;this.send(new mavlink20.messages.command_long(this.target.systemId,this.target.componentId,command,p.attempt-1,...params),0).catch(reject);p.timer=setTimeout(()=>{if(p.attempt<3)attempt();else{this.commandPending.delete(command);reject(new Error(`命令 ${command} 未收到 COMMAND_ACK`))}},COMMAND_TIMEOUT)};this.commandPending.set(command,p);attempt()})}
 onCommandAck(m){const p=this.commandPending.get(m.command);if(!p)return;if(m.result===5){clearTimeout(p.timer);p.timer=setTimeout(()=>{this.commandPending.delete(m.command);p.reject(new Error(`命令 ${m.command} 长时间无进度`))},5000);this.emit('commandProgress',{command:m.command,progress:m.progress});return}clearTimeout(p.timer);this.commandPending.delete(m.command);const result={command:m.command,result:m.result,progress:m.progress,resultParam2:m.result_param2};m.result===0?p.resolve(result):p.reject(Object.assign(new Error(`命令被拒绝，MAV_RESULT=${m.result}`),{result}))}
 listLogs(){this.logEntries.clear();this.send(new mavlink20.messages.log_request_list(this.target.systemId,this.target.componentId,0,65535),3).catch(e=>this.emit('error',e));return{started:true}}
 onLogEntry(m){if(Number(m.id)===0&&Number(m.num_logs)===0){this.logEntries.clear();this.emit('logs',[]);return}const entry={id:m.id,numLogs:m.num_logs,lastLogNum:m.last_log_num,timeUtc:m.time_utc,size:m.size};this.logEntries.set(entry.id,entry);this.emit('logs',[...this.logEntries.values()].sort((a,b)=>b.id-a.id))}
 downloadLog(entry,destination){if(this.download)throw new Error('已有日志正在下载');fs.mkdirSync(path.dirname(destination),{recursive:true});let offset=0;if(fs.existsSync(destination))offset=Math.min(fs.statSync(destination).size,entry.size);const fd=fs.openSync(destination,offset?'r+':'w+');this.download={entry,destination,fd,nextOffset:offset,received:new Map(),receivedBytes:offset,requestStart:offset,timer:null,resolve:null,reject:null};const promise=new Promise((resolve,reject)=>{this.download.resolve=resolve;this.download.reject=reject});this.requestLogChunk(offset);return promise}
 requestLogChunk(ofs){const d=this.download;if(!d)return;d.requestStart=ofs;clearTimeout(d.timer);this.send(new mavlink20.messages.log_request_data(this.target.systemId,this.target.componentId,d.entry.id,ofs,Math.min(8190,d.entry.size-ofs)),3).catch(e=>this.cancelDownload(e.message));d.timer=setTimeout(()=>this.requestLogChunk(d.nextOffset),1200)}
 onLogData(m){const d=this.download;if(!d||m.id!==d.entry.id)return;clearTimeout(d.timer);const bytes=(typeof m.data==='string'?Buffer.from(m.data,'latin1'):Buffer.from(m.data||[])).subarray(0,m.count),ofs=Number(m.ofs);if(!d.received.has(ofs)&&ofs>=d.nextOffset){fs.writeSync(d.fd,bytes,0,bytes.length,ofs);d.received.set(ofs,bytes.length);d.receivedBytes+=bytes.length}while(d.received.has(d.nextOffset)){const n=d.received.get(d.nextOffset);d.received.delete(d.nextOffset);d.nextOffset+=n}this.emit('logProgress',{id:m.id,received:Math.min(d.receivedBytes,d.entry.size),total:d.entry.size});if(d.nextOffset>=d.entry.size){clearTimeout(d.timer);fs.ftruncateSync(d.fd,d.entry.size);fs.closeSync(d.fd);this.send(new mavlink20.messages.log_request_end(this.target.systemId,this.target.componentId),3).catch(()=>{});const done=d.resolve;this.download=null;done({path:d.destination,size:d.entry.size})}else if(bytes.length<90||d.nextOffset>=d.requestStart+8190)this.requestLogChunk(d.nextOffset);else d.timer=setTimeout(()=>this.requestLogChunk(d.nextOffset),1200)}
 cancelDownload(reason){const d=this.download;if(!d)return;clearTimeout(d.timer);try{fs.closeSync(d.fd)}catch{}this.download=null;d.reject(new Error(reason))}
 eraseLogs(){if(this.telemetry.armed)return Promise.reject(new Error('飞控已解锁，禁止删除板载日志'));if(this.download)return Promise.reject(new Error('日志正在下载，禁止同时删除'));return this.send(new mavlink20.messages.log_erase(this.target.systemId,this.target.componentId),3).then(result=>{setTimeout(()=>{if(this.connected)this.listLogs()},1000);return result})}
 waitForHilState(expected,timeoutMs=2500){if(!!this.telemetry.hilEnabled===expected)return Promise.resolve(true);return new Promise((resolve,reject)=>{const onHeartbeat=telemetry=>{if(!!telemetry.hilEnabled===expected){cleanup();resolve(true)}};const cleanup=()=>{clearTimeout(timer);this.off('heartbeat',onHeartbeat)};const timer=setTimeout(()=>{cleanup();reject(new Error(`飞控 HEARTBEAT 未确认 HIL=${expected?1:0}`))},timeoutMs);this.on('heartbeat',onHeartbeat)})}
 sendRcOverride(channels=[],release=false){const pwm=Array.from({length:8},(_,index)=>{if(release)return 0;const value=Number(channels[index]);return channels[index]==null||value===65535?65535:integer(value,1000,2000,1500)}),extensions=Array(10).fill(65535);return this.send(new mavlink20.messages.rc_channels_override(this.target.systemId,this.target.componentId,...pwm,...extensions),0,{replaceKey:'RC_CHANNELS_OVERRIDE'})}
 sendHilSensor(s={}){return this.send(new mavlink20.messages.hil_sensor(uint64Pair(s.timeUsec),float32(s.xacc),float32(s.yacc),float32(s.zacc),float32(s.xgyro),float32(s.ygyro),float32(s.zgyro),float32(s.xmag),float32(s.ymag),float32(s.zmag),float32(s.absPressure,1013.25),float32(s.diffPressure),float32(s.pressureAlt),float32(s.temperature,25),0x1fff,0),1,{replaceKey:'HIL_SENSOR'})}
 sendHilGps(s={}){return this.send(new mavlink20.messages.hil_gps(uint64Pair(s.timeUsec),integer(s.fixType,0,255,3),integer(s.lat,-900000000,900000000),integer(s.lon,-1800000000,1800000000),integer(s.alt,-2147483648,2147483647),integer(s.eph,0,65535,80),integer(s.epv,0,65535,120),integer(s.vel,0,65535),integer(s.vn,-32768,32767),integer(s.ve,-32768,32767),integer(s.vd,-32768,32767),integer(s.cog,0,65535,65535),integer(s.satellites,0,255,18),0,65535),1,{replaceKey:'HIL_GPS'})}
 sendHilTruth(s={}){const originLat=bounded(s.originLat,-90,90,31.230123),originLon=bounded(s.originLon,-180,180,121.473456),p=vector(s.p,3),v=vector(s.v,3),w=vector(s.w,3),specific=vector(s.specific,3),metersPerLon=Math.max(1,111111*Math.cos(originLat*Math.PI/180)),lat=integer((originLat+p[0]/111111)*1e7,-900000000,900000000),lon=integer((originLon+p[1]/metersPerLon)*1e7,-1800000000,1800000000),cmps=value=>integer(value*100,-32768,32767),mg=value=>integer(value/G*1000,-32768,32767);return this.send(new mavlink20.messages.hil_state_quaternion(uint64Pair(s.timeUsec),quaternion(s.q),float32(w[0]),float32(w[1]),float32(w[2]),lat,lon,integer((finite(s.originAltMsl)-p[2])*1000,-2147483648,2147483647),cmps(v[0]),cmps(v[1]),cmps(v[2]),integer(Math.hypot(v[0],v[1])*100,0,65535),integer(Math.hypot(...v)*100,0,65535),mg(specific[0]),mg(specific[1]),mg(specific[2])),1,{replaceKey:'HIL_STATE_QUATERNION'})}
}
module.exports={VehicleSession,mavlink20,encodeParam,decodeParam,int64ToNumber,uint64Pair};
