import {useEffect,useState} from 'react';
import {Cpu,Link2,MoreHorizontal,Radio,RefreshCw,Search,Upload,Usb,X} from 'lucide-react';
import {Button,Panel,Progress,Tag} from '../components/UI';
import type {FirmwareProgress,FirmwareSelection} from '../desktop-api';
import {BOOT_BOARD_NAME,BOOT_PROTOCOL_VERSION} from '../lib/boot-protocol-generated';
import {useFlight} from '../services/FlightContext';

const phaseLabels:Record<string,string>={
 'requesting-bootloader':'请求飞控进入 Bootloader','waiting-bootloader':'等待 USB CDC 重枚举',
 erasing:'擦除非活动分区',uploading:'传输固件',verifying:'设备端 CRC32 与向量表校验',
 rebooting:'启动候选固件','waiting-trial':'等待候选固件启动','trial-running':'候选固件健康确认中',
 'verifying-confirmation':'读取元数据确认最终活动分区',completed:'升级及确认完成',cancelled:'升级已取消',failed:'升级失败',
};

export default function DevicesPage(_props:{connected:boolean;setConnected:(v:boolean)=>void}){
 const f=useFlight();
 const [firmware,setFirmware]=useState<FirmwareSelection|null>(null);
 const [firmwareProgress,setFirmwareProgress]=useState<FirmwareProgress|null>(null);
 const [firmwareBusy,setFirmwareBusy]=useState(false);
 useEffect(()=>window.aeroLink?.onFirmwareProgress(setFirmwareProgress),[]);
 const connect=async(path:string)=>{if(f.link.connected&&f.link.path===path)await f.disconnect();else{if(f.link.connected)await f.disconnect();await f.connect(path)}};
 const auto=async()=>{await f.refreshPorts();if(f.ports.length===1)await f.connect(f.ports[0].path)};
 const chooseFirmware=async()=>{const selected=await window.aeroLink?.selectFirmware();if(selected&&!selected.canceled){setFirmware(selected);setFirmwareProgress(null)}};
 const startFirmware=async()=>{if(!firmware?.path||!window.aeroLink)return;if(!window.confirm('确认开始 A/B 升级？必须拆除螺旋桨并断开电机动力电源。'))return;setFirmwareBusy(true);try{await window.aeroLink.startFirmwareUpdate({path:firmware.path})}finally{setFirmwareBusy(false)}};
 const closeFirmware=()=>{if(!firmwareBusy){setFirmware(null);setFirmwareProgress(null)}};
 const activeProgress=firmwareProgress?.percent??0;
 const cancellationLocked=['verifying','rebooting','waiting-trial','trial-running','verifying-confirmation'].includes(firmwareProgress?.phase||'');

 return <div className="devices-page page-fill"><h2>设备连接</h2><div className="device-grid"><div className="device-main">
  <div className="device-toolbar"><button className="active">全部</button><button>USB CDC</button><button disabled>UDP</button><button disabled>TCP</button><button disabled>CAN</button><span/><Button onClick={()=>void f.refreshPorts()}><RefreshCw/> 扫描设备</Button><Button onClick={()=>void auto()}><Link2/> 自动连接</Button><Button disabled={!f.link.connected||!!f.telemetry.armed||firmwareBusy} title={f.telemetry.armed?'飞控已解锁，禁止升级':'选择经过校验的 .uavfw A/B 固件包'} onClick={()=>void chooseFirmware()}><Upload/> 固件升级</Button><Button><MoreHorizontal/></Button></div>
  <Panel className="device-table"><table><thead><tr><th>设备名称</th><th>类型</th><th>端口</th><th>VID / PID</th><th>状态</th><th>接收</th><th>发送</th><th>丢包率</th><th>操作</th></tr></thead><tbody>{f.ports.length?f.ports.map(p=>{const active=f.link.path===p.path&&f.link.connected;return <tr className={active?'selected':''} key={p.path}><td><b><Usb/>{p.friendlyName||p.manufacturer||'USB CDC 设备'}</b><small>{p.serialNumber||'未提供序列号'}</small></td><td>USB CDC ACM</td><td>{p.path}</td><td>{p.vendorId||'—'} / {p.productId||'—'}</td><td>{active?<Tag>已连接</Tag>:<Tag kind="orange">可用</Tag>}</td><td>{active?formatBytes(f.link.rxBytes):'—'}</td><td>{active?formatBytes(f.link.txBytes):'—'}</td><td>{active?`${f.link.lossRate.toFixed(2)}%`:'—'}</td><td><Button kind={active?'danger':'primary'} onClick={()=>void connect(p.path)}>{active?'断开':'连接'}</Button></td></tr>}):<tr><td colSpan={9}><div className="empty-state">未发现 COM 端口。连接 STM32 USB CDC 后点击“扫描设备”。</div></td></tr>}</tbody></table><footer>共 {f.ports.length} 个串口设备　｜　MAVLink：{f.link.connected?'已连接':'未连接'}</footer></Panel>
  <div className="device-bottom"><Panel title="连接日志"><div className="connection-log">{f.messages.length?f.messages.slice(0,10).map(m=><div key={m.time}>{new Date(m.time).toLocaleTimeString('zh-CN',{hour12:false})}　<span>[STATUSTEXT]</span>　{m.text}</div>):<div>等待飞控 HEARTBEAT 和 STATUSTEXT…</div>}</div></Panel><Panel title="诊断工具"><div className="diagnostics">{[['端口检测','重新扫描 Windows COM 设备'],['心跳检查','5 秒未收到 HEARTBEAT 判定断线'],['MAVLink 检查','CRC、序号与丢包统计'],['带宽统计','实时收发字节'],['固件校验',`Bootloader v${BOOT_PROTOCOL_VERSION} / CRC32 + SHA-256`]].map((x,i)=><div key={x[0]}>{i===0?<Search/>:i===2?<Radio/>:<Cpu/>}<b>{x[0]}</b><p>{x[1]}</p><Button disabled={i>0} onClick={()=>i===0&&void f.refreshPorts()}>检测</Button></div>)}</div></Panel></div>
  <Panel title="快速命令"><div className="quick-actions"><Button disabled={!f.link.connected} onClick={()=>window.confirm('确认重启飞控？')&&void f.sendCommand(246,[1,0,0,0,0,0,0])}>重启飞控</Button>{[1,2,3,4].map(m=><Button key={m} disabled={!f.link.connected||!!f.telemetry.armed} title="10% 输出，持续 1 秒；飞控必须未解锁" onClick={()=>window.confirm(`确认测试电机 ${m}？螺旋桨必须拆除，输出 10%，持续 1 秒。` )&&void f.testActuator(m,.1,1)}>测试电机 {m}</Button>)}<Button disabled={!f.link.connected||!!f.telemetry.armed} onClick={()=>window.confirm('进入 Bootloader 后需在 30 秒内建立升级会话，是否继续？')&&void f.sendCommand(246,[3,0,0,0,0,0,0])}>进入 Bootloader</Button><Button kind="danger" disabled={!f.link.connected} onClick={()=>void f.disconnect()}>断开连接</Button></div></Panel>
 </div><Panel title="设备详情" className="device-detail"><div className="device-title"><Usb/><b>{f.link.connected?'飞控主控':'未连接飞控'}</b>{f.link.connected?<Tag>已连接</Tag>:<Tag kind="red">未连接</Tag>}<small>{f.link.path||'请选择 COM 端口'}</small></div><div className="detail-tabs"><b>概览</b><span>串口设置</span><span>MAVLink 统计</span><span>链路质量</span></div><div className="device-cards"><Panel title="基本信息"><div className="dense-list"><span>设备类型　USB CDC ACM</span><span>端口　　　{f.link.path||'—'}</span><span>线编码　　921600 / 8N1</span><span>协议　　　MAVLink 2</span><span>Bootloader {BOOT_BOARD_NAME} / v{BOOT_PROTOCOL_VERSION}</span></div></Panel><Panel title="MAVLink 心跳"><div className="dense-list"><span>状态　　　{f.link.connected?'在线':'离线'}</span><span>最后心跳　{f.link.lastHeartbeat?new Date(f.link.lastHeartbeat).toLocaleTimeString('zh-CN',{hour12:false}):'—'}</span><span>接收包　　{f.link.rxPackets}</span><span>丢失包　　{f.link.lostPackets}</span></div></Panel><Panel title="消息频率"><div className="dense-list">{Object.entries(f.link.messageRates).slice(0,12).map(([n,h])=><span key={n}>{n}　{h.toFixed(1)} Hz</span>)}</div></Panel><Panel title="链路统计"><div className="dense-list"><span>接收　{formatBytes(f.link.rxBytes)}</span><span>发送　{formatBytes(f.link.txBytes)}</span><span>丢包率　{f.link.lossRate.toFixed(3)}%</span></div></Panel><Panel title="链路质量"><div className="signal-bars">▂▃▄▅▆　{Math.max(0,100-f.link.lossRate).toFixed(0)}%</div><Progress value={Math.max(0,100-f.link.lossRate)}/></Panel></div></Panel></div>
  {firmware&&<div className="firmware-overlay"><div className="firmware-dialog"><header><div><Upload/><span><b>A/B 固件升级</b><small>{firmware.version} · {firmware.gitSha?.slice(0,12)}</small></span></div><button disabled={firmwareBusy} onClick={closeFirmware}><X/></button></header><div className="firmware-safety">仅在拆桨、断开电机动力电源且飞控未解锁时升级。CRC32 只保证完整性，不验证发布者身份。</div><div className="firmware-images">{Object.entries(firmware.slots||{}).map(([slot,image])=><div key={slot}><b>Slot {slot}</b><span>{formatBytes(image.size)}</span><code>{image.crc32}</code></div>)}</div><div className="firmware-status"><b>{phaseLabels[firmwareProgress?.phase||'']||'等待开始'}</b><span>{firmwareProgress?.message||`${activeProgress}%`}</span><Progress value={activeProgress}/>{firmwareProgress?.slot&&<small>目标 / 最终确认分区：Slot {firmwareProgress.slot}</small>}</div><footer><Button disabled={!firmwareBusy||cancellationLocked} kind="danger" title={cancellationLocked?'固件已进入提交或试运行阶段，不能再中止':''} onClick={()=>void window.aeroLink?.cancelFirmwareUpdate()}>取消升级</Button><Button kind="primary" disabled={firmwareBusy||firmwareProgress?.phase==='completed'} onClick={()=>void startFirmware()}>开始升级</Button></footer></div></div>}
 </div>;
}

const formatBytes=(n:number)=>n>=1048576?`${(n/1048576).toFixed(1)} MB`:n>=1024?`${(n/1024).toFixed(1)} KB`:`${n} B`;
