import {CircleDot,Download,Save,Search,Settings2,Upload} from 'lucide-react';
import {useMemo,useState} from 'react';
import {Button,Panel,SelectBox,Tag} from '../components/UI';
import {useFlight} from '../services/FlightContext';
import metadata from '../data/parameter-metadata.json';

type Meta={unit?:string;group:string;min?:number;max?:number;default?:number;description:string};const meta=metadata as Record<string,Meta>;
const groupOf=(id:string)=>meta[id]?.group||(/^(MC_|ATC_|RATE_)/.test(id)?'姿态控制':/^(GPS_|EKF|INS_)/.test(id)?'导航定位':/^(BAT_|MOT_|PWM_)/.test(id)?'动力系统':/^(ARM|FS_|RTL_)/.test(id)?'安全返航':'其他');
export default function ParametersPage(){
 const f=useFlight(),[query,setQuery]=useState(''),[group,setGroup]=useState('全部参数'),[draft,setDraft]=useState<Record<string,string>>({}),[selected,setSelected]=useState(''),[busy,setBusy]=useState('');
 const groups=useMemo(()=>{const m=new Map<string,number>();f.parameters.forEach(p=>m.set(groupOf(p.id),(m.get(groupOf(p.id))||0)+1));return[['全部参数',f.parameters.length],...[...m.entries()]] as [string,number][]},[f.parameters]);
 const rows=f.parameters.filter(p=>(group==='全部参数'||groupOf(p.id)===group)&&p.id.toLowerCase().includes(query.toLowerCase())).slice(0,120),expected=Math.max(0,...f.parameters.map(p=>p.count)),percent=expected?Math.min(100,Math.round(f.parameters.length/expected*100)):0;
 const write=async(id:string)=>{const p=f.parameters.find(x=>x.id===id);if(!p)return;const value=Number(draft[id]??p.value),md=meta[id];if(!Number.isFinite(value))return alert('参数值必须是数字');if(md?.min!=null&&(value<md.min||value>(md.max??value)))return alert(`允许范围：${md.min} ~ ${md.max}`);setBusy(id);try{await f.setParameter(id,value,p.type);setDraft(v=>{const n={...v};delete n[id];return n})}finally{setBusy('')}};
 const importFile=async()=>{const result=await f.importParameters();if(result.canceled)return;const known=new Set(f.parameters.map(p=>p.id)),next:Record<string,string>={};for(const item of result.parameters)if(known.has(item.id))next[item.id]=String(item.value);setDraft(value=>({...value,...next}));alert(`已载入 ${Object.keys(next).length} 项；请检查差异后逐项或批量写入。`)};
 const writeAll=async()=>{const ids=Object.keys(draft);if(!ids.length||!window.confirm(`确认依次写入 ${ids.length} 个参数？每项必须收到 PARAM_VALUE 回读。`))return;for(const id of ids)await write(id)};
 const restoreSelected=()=>{const value=meta[selected]?.default;if(value==null)return alert('该参数没有本地默认值元数据');setDraft(current=>({...current,[selected]:String(value)}))};
 const command=(id:number,params:number[],text:string)=>{if(window.confirm(text))void f.sendCommand(id,params)};
 return <div className="parameter-page page-fill"><div className="page-heading"><h2>参数配置</h2>{percent===100&&expected?<Tag>{f.parameters.length} 项同步完成</Tag>:<Tag kind="orange">{f.parameters.length?`同步 ${percent}%`:'尚未同步'}</Tag>}</div><div className="param-tabs">{['飞行控制参数','姿态环 PID','角速度环 PID','位置控制','传感器标定','安全与返航','高级参数'].map((x,i)=><button className={i===0?'active':''} key={x}><Settings2/>{x}</button>)}</div><div className="param-main">
 <Panel title="参数分组" className="groups"><div className="search"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索参数"/></div>{groups.map(([n,c])=><button className={group===n?'active':''} onClick={()=>setGroup(n)} key={n}><CircleDot/>{n}<span>{c}</span></button>)}</Panel>
 <div className="param-center"><Panel className="param-table" title={<div className="table-tools"><div className="search"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="参数名 / 关键字"/></div><SelectBox>{group}</SelectBox></div>} action={<div className="button-row"><Button disabled={!f.link.connected} onClick={()=>void f.requestParameters()}><Download/> 读取飞控参数</Button><Button onClick={()=>void importFile()}><Upload/> 导入参数</Button><Button disabled={!f.parameters.length} onClick={()=>void f.exportParameters()}><Save/> 导出参数</Button></div>}><table><thead><tr><th>参数名</th><th>当前值</th><th>单位</th><th>类型</th><th>范围</th><th>说明</th><th>操作</th></tr></thead><tbody>{rows.length?rows.map(p=>{const md=meta[p.id];return <tr className={selected===p.id?'selected':''} onClick={()=>setSelected(p.id)} key={`${p.componentId}:${p.id}`}><td>☆ {p.id}</td><td><input className="param-value-input" value={draft[p.id]??String(p.value)} onChange={e=>setDraft(v=>({...v,[p.id]:e.target.value}))}/></td><td>{md?.unit||'—'}</td><td>{p.type===6?'INT32':p.type===9?'REAL32':`TYPE ${p.type}`}</td><td>{md?.min!=null?`${md.min} ~ ${md.max}`:'飞控定义'}</td><td>{md?.description||'未知参数（仍可读写）'}</td><td><Button disabled={busy===p.id} kind={draft[p.id]!=null?'primary':''} onClick={()=>void write(p.id)}>{busy===p.id?'等待确认':'写入'}</Button></td></tr>}):<tr><td colSpan={7}><div className="empty-state">连接飞控后点击“读取飞控参数”</div></td></tr>}</tbody></table><div className="pagination">收到 {f.parameters.length} / {expected||'?'} 项　当前显示 {rows.length} 项</div></Panel>
 <div className="tuning-row"><LiveParamPanel title="姿态环 PID" names={['MC_ROLL_P','MC_ROLL_I','MC_ROLL_D']} values={f.parameters}/><LiveParamPanel title="角速度环 PID" names={['MC_RATE_P','MC_RATE_I','MC_RATE_D']} values={f.parameters}/><Panel title="安全命令"><div className="cal-list"><div><span>运行预检</span><Button onClick={()=>void f.sendCommand(401)}>执行</Button></div><div><span>保存参数到 Flash</span><Button onClick={()=>command(245,[1,0,0,0,0,0,0],'确认要求飞控保存参数？')}>保存</Button></div><div><span>重启飞控</span><Button onClick={()=>command(246,[1,0,0,0,0,0,0],'确认重启飞控？')}>重启</Button></div></div></Panel><Panel title="传感器标定"><div className="cal-list"><div><span>陀螺仪</span><Button onClick={()=>command(241,[1,0,0,0,0,0,0],'开始陀螺仪标定？飞行器必须静止且未解锁。')}>开始</Button></div><div><span>磁力计</span><Button onClick={()=>command(241,[0,1,0,0,0,0,0],'开始磁力计标定？')}>开始</Button></div><div><span>加速度计</span><Button onClick={()=>command(241,[0,0,0,0,1,0,0],'开始加速度计标定？')}>开始</Button></div></div></Panel></div>
 <div className="bottom-actions"><Button kind="primary" disabled={!f.link.connected} onClick={()=>void f.requestParameters()}><Download/> 读取参数</Button><Button kind="success" disabled={!selected} onClick={()=>selected&&void write(selected)}><Upload/> 写入选中项</Button><Button kind="success" disabled={!Object.keys(draft).length} onClick={()=>void writeAll()}>写入全部修改</Button><Button disabled={!selected||meta[selected]?.default==null} onClick={restoreSelected}>载入默认值</Button><Button kind="primary" onClick={()=>command(245,[1,0,0,0,0,0,0],'确认保存到飞控 Flash？')}><Save/> 保存到飞控</Button></div></div>
 <div className="param-right"><Panel title="参数同步状态" action={percent===100&&expected?<Tag>同步完成</Tag>:<Tag kind="orange">等待</Tag>}><div className="sync-ring">{percent}%</div><div className="dense-list"><span>飞控 → 地面站　{f.parameters.length}</span><span>目标系统　　　{f.link.connected?'在线':'离线'}</span><span>协议　　　　　MAVLink PARAM</span><span>缺项策略　　　按索引补读 ×3</span></div></Panel><Panel title="已修改未写入"><div className="dense-list">{Object.keys(draft).length?Object.entries(draft).map(([id,v])=><span key={id}>{id}　→　{v}</span>):<span>没有待写入修改</span>}</div></Panel><Panel title="参数分类统计">{groups.slice(1).map(([n,c])=><p key={n}>●　{n}　{c}</p>)}</Panel><Panel title="配置来源"><div className="dense-list"><span>实时值　飞控 PARAM_VALUE</span><span>元数据　本地 JSON</span><span>写入确认　同名 PARAM_VALUE</span></div></Panel></div></div></div>
}
function LiveParamPanel({title,names,values}:{title:string;names:string[];values:{id:string;value:number}[]}){return <Panel title={title} action={<Tag kind="blue">实时</Tag>}>{names.map(n=><div className="pid-line" key={n}><span>{n.replace(/^MC_/,'')}</span><input readOnly value={values.find(p=>p.id===n)?.value??'—'}/></div>)}</Panel>}
