import { useEffect,useMemo,useState } from 'react';
import { FastForward, Pause, Play, Rewind, Upload } from 'lucide-react';
import type { ChartPoint,Telemetry } from '../types';
import { AreaSpark, MiniLineChart } from '../components/Charts';
import { DroneVisual, MapVisual } from '../components/Visuals';
import { Button, Metric, Panel, Tag } from '../components/UI';

type LocalLog={name:string;path:string;size:number;time:number;source:string};
type Replay={file:string;size:number;format:string;records:number;durationUs:number;charts:Array<ChartPoint&{lat?:number;lon?:number}>;trail:{lat:number;lon:number}[];events:{text:string;severity:number;t:number}[];final:Telemetry};
export default function ReplayPage({telemetry:_telemetry}:{telemetry?:Telemetry}){
 const [files,setFiles]=useState<LocalLog[]>([]),[selected,setSelected]=useState(''),[replay,setReplay]=useState<Replay|null>(null),[loading,setLoading]=useState(false),[playing,setPlaying]=useState(false),[cursor,setCursor]=useState(0),[speed,setSpeed]=useState(1);
 useEffect(()=>{window.aeroLink?.listLocalLogs().then(v=>{setFiles(v);if(v[0])setSelected(v[0].path)}).catch(()=>{})},[]);
 useEffect(()=>{if(!playing||!replay?.charts.length)return;const id=setInterval(()=>setCursor(v=>{const n=Math.min(replay.charts.length-1,v+Math.max(1,Math.round(speed)));if(n===replay.charts.length-1)setPlaying(false);return n}),50);return()=>clearInterval(id)},[playing,replay,speed]);
 const load=async()=>{if(!selected||!window.aeroLink)return;setLoading(true);try{const d=await window.aeroLink.loadReplay(selected);setReplay(d);setCursor(0)}finally{setLoading(false)}};
 const point=replay?.charts[cursor],data=replay?.charts.slice(0,cursor+1)||[],duration=replay?.durationUs||0;
 const stats=useMemo(()=>{const c=replay?.charts||[];return{maxAlt:c.length?Math.max(...c.map(x=>x.altitude)):0,avgSpeed:c.length?c.reduce((a,b)=>a+b.speed,0)/c.length:0,maxSpeed:c.length?Math.max(...c.map(x=>x.speed)):0,minVoltage:c.length?Math.min(...c.filter(x=>x.voltage>0).map(x=>x.voltage)):0}},[replay]);
 return <div className="replay-page page-fill"><div className="page-heading"><h2>回放分析</h2><select value={selected} onChange={e=>setSelected(e.target.value)}>{files.length?files.map(x=><option value={x.path} key={x.path}>{x.name}　{formatBytes(x.size)}</option>):<option value="">暂无本地 .tlog / .bin</option>}</select><Button onClick={()=>void load()} disabled={!selected||loading}><Upload/> {loading?'解析中…':'加载日志'}</Button><span>{replay&&`${replay.format} · ${replay.records.toLocaleString()} 记录`}</span></div><div className="replay-grid">
 <Panel title="3D 回放" className="replay-scene"><div className="replay-data"><b>时间<br/>{point?new Date(point.t).toLocaleTimeString('zh-CN',{hour12:false}):'--:--:--'}</b><p>经度　{point?.lon?.toFixed(7)||'—'}</p><p>纬度　{point?.lat?.toFixed(7)||'—'}</p><p>高度　{point?.altitude.toFixed(1)||'0.0'} m</p><p>地速　{point?.speed.toFixed(1)||'0.0'} m/s</p><p>航向　{point?.yaw.toFixed(0)||'0'}°</p><p>状态　<Tag kind={replay?'green':'orange'}>{replay?'已加载':'等待日志'}</Tag></p></div><DroneVisual compact roll={point?.roll||0} pitch={point?.pitch||0} yaw={point?.yaw||0}/><div className="play-controls"><Button onClick={()=>setPlaying(true)} disabled={!replay}><Play/> 播放</Button><Button onClick={()=>setPlaying(false)}><Pause/> 暂停</Button><Button onClick={()=>setCursor(v=>Math.max(0,v-100))}><Rewind/> 后退</Button><Button onClick={()=>setCursor(v=>Math.min((replay?.charts.length||1)-1,v+100))}><FastForward/> 前进</Button><button onClick={()=>setSpeed(v=>v>=4?1:v*2)}>{speed.toFixed(1)}×</button><span>{cursor+1} / {replay?.charts.length||0}</span></div></Panel>
 <Panel title="地图回放" className="replay-map"><MapVisual large points={replay?.trail||[]} hasFix={!!replay?.trail.length}/><div className="map-metrics"><Metric label="轨迹点" value={replay?.trail.length||0}/><Metric label="最大高度" value={`${stats.maxAlt.toFixed(1)} m`}/><Metric label="平均速度" value={`${stats.avgSpeed.toFixed(1)} m/s`}/><Metric label="日志时长" value={formatDuration(duration/1000)}/></div></Panel>
 <div className="replay-side"><Panel title="回放完整性"><div className="score-ring"><b>{replay?Math.max(0,100-Math.min(100,replay.final.link?.lossRate||0)).toFixed(0):0}</b><span>链路评分</span></div><p>已解析消息　<Tag>{replay?.records||0}</Tag></p><p>轨迹点　　　<Tag>{replay?.trail.length||0}</Tag></p><p>状态事件　　<Tag>{replay?.events.length||0}</Tag></p></Panel><Panel title={`STATUSTEXT 事件 (${replay?.events.length||0})`}>{replay?.events.slice(0,8).map((e,i)=><p className={e.severity<=3?'red':'orange'} key={i}>{e.text}</p>)||<p>暂无事件</p>}</Panel></div>
 <Panel title="本地日志" className="event-list">{files.slice(0,12).map(x=><p onClick={()=>setSelected(x.path)} key={x.path}><span>{new Date(x.time).toLocaleDateString('zh-CN')}</span>{x.name}</p>)}</Panel>
 <Panel className="timeline"><input type="range" min={0} max={Math.max(0,(replay?.charts.length||1)-1)} value={cursor} onChange={e=>setCursor(Number(e.target.value))}/><div>开始　　　　　　　　　　　　　　　　　　　{formatDuration(duration/2000)}　　　　　　　　　　　　　　　　　　　结束</div></Panel>
 <Panel title="数据曲线（使用同一 MAVLink 数据模型）" className="replay-charts"><div className="five-charts"><div><b>高度 (m)</b><AreaSpark data={data} keyName="altitude"/></div><div><b>地速 (m/s)</b><AreaSpark data={data} keyName="speed"/></div><MiniLineChart data={data} keys={['roll','pitch','yaw']} title="姿态 (°)" height={100}/><div><b>电压 (V)</b><AreaSpark data={data} keyName="voltage"/></div><MiniLineChart data={data} keys={['m1','m2','m3','m4']} title="电机输出 (%)" height={100}/></div></Panel>
 <div className="replay-stats"><Panel title="关键统计"><div className="stats-grid"><Metric label="文件大小" value={formatBytes(replay?.size||0)}/><Metric label="最大高度" value={`${stats.maxAlt.toFixed(1)} m`}/><Metric label="平均速度" value={`${stats.avgSpeed.toFixed(1)} m/s`}/><Metric label="最大地速" value={`${stats.maxSpeed.toFixed(1)} m/s`}/><Metric label="最低电压" value={stats.minVoltage?`${stats.minVoltage.toFixed(1)} V`:'—'}/><Metric label="消息记录" value={(replay?.records||0).toLocaleString()}/></div></Panel><Panel title="说明"><p>`.tlog` 记录原始 USB CDC 接收块及主机时间戳。</p><p>回放 Worker 重新调用实时 `VehicleSession` 的 CRC 校验、消息路由和统一模型。</p></Panel></div>
 </div></div>
}
const formatBytes=(n:number)=>n>=1048576?`${(n/1048576).toFixed(1)} MB`:n>=1024?`${(n/1024).toFixed(1)} KB`:`${n} B`;
const formatDuration=(ms:number)=>{const s=Math.max(0,Math.round(ms/1000));return`${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`};
